id: opecha:P000658
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1050
  title: ཕྱག་དྲུག་ཡེ་ཤེས་ཀྱི་མགོན་པོ་ལ་བརྟེན་པའི་གཏོར་བཟློག་བདུད་སྡེའི་དཔུང་འཇོམས་གནམ་ལྕགས་རྡོ་རྗེའི་ཐོག་མདའ་ཚ་དཔལ
  volume: ''
  author: ''
