id: I0D9FBBB9
legacy_id: P000658
ocr_import_info:
  bdrc_scan_id: W1CZ1050
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:47:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:46:56.912766+00:00'
last_modified: 2022-08-31 02:47:10.117770
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1050
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1050
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་དྲུག་ཡེ་ཤེས་ཀྱི་མགོན་པོ་ལ་བརྟེན་པའི་གཏོར་བཟློག་བདུད་སྡེའི་དཔུང་འཇོམས་གནམ་ལྕགས་རྡོ་རྗེའི་ཐོག་མདའ་ཚ་དཔལ།
  author: ཆེ་ཤོས ༠༣་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེ།
statistics:
  ocr_word_mean_confidence_index: 0.5221772301300459
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I1CZ1326:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1326
      total_pages: 80
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1326.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5221772301300459
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
